name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4


      - name: Grant Execute Permission for Gradle
        run: |
          chmod +x fabric/gradlew
          chmod +x neoforge/gradlew

      - name: Build with Gradle
        run: |
          (cd fabric && ./gradlew build) &
          (cd neoforge && ./gradlew build)

      - name: mc-publish
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: Ye73E82r
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 476789
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}